[sudo]
style = 'bold green'
symbol = '🧙 '
disabled = false


[time]
disabled = false
format = '[$time]($style) '
time_format = '%R'

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
